export enum BAD_REQ_ERROR_ENUM {
    ALREADY_LOGGED = "ALREADY_LOGGED",
    REFRESH_TOKEN_MISSING = "REFRESH_TOKEN_MISSING",
    RECOVER_TOKEN_MISSING = "RECOVER_TOKEN_MISSING",
    INVALID_PARAMETER_VALUE = "INVALID_PARAMETER_VALUE"
}