import {registerEnumType} from "type-graphql";

export enum DATA_ERROR_ENUM {
    EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
    ITEM_NOT_EXISTING = "ITEM_NOT_EXISTING",
    AMOUNT_NOT_AVAILABLE = "AMOUNT_NOT_AVAILABLE",
    ADDRESS_NOT_EXISTING = "ADDRESS_NOT_EXISTING",
    ITEM_ON_HOLD = "ITEM_ON_HOLD",
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
}

registerEnumType(DATA_ERROR_ENUM, {
    name: "DATA_ERROR_ENUM"
});